project:
  machine_name: well
  prefix: WELL
  human_name: Well
  profile:
    name: headless_lightning
  local:
    protocol: http
    hostname: 'local.${project.machine_name}.com'
git:
  default_branch: master
  remotes: {  }
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: 'well.local'
    ci: ''
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: {  }
  ci:
    enable: {  }
    uninstall: {  }
  dev:
    enable: {  }
    uninstall: {  }
  test:
    enable: {  }
    uninstall: {  }
  prod:
    enable: {  }
    uninstall: {  }
target-hooks:
  frontend-setup:
    dir: '${docroot}'
    command: 'echo ''No frontend-setup configured.'''
  frontend-build:
    dir: '${docroot}'
    command: 'echo ''No frontend-build configured.'''
  pre-config-import:
    dir: '${docroot}'
    command: 'echo ''No pre-config-import configured.'''
  post-deploy-build:
    dir: '${deploy.dir}/docroot'
    command: 'echo ''No post-deploy build configured.'''
  post-setup-build:
    dir: '${docroot}'
    command: 'echo ''No post-setup build configured.'''
  post-deploy:
    dir: '${docroot}'
    command: 'echo ''No post-deploy build configured.'''
behat:
  web-driver: selenium
